### ISSUE TITLE
Alternative credentials; NuGet Package; versioning

### ISSUE THREAD

**Issue by oxygenius** [antiduh/nsspi#9]
Hi Kevin,

Thank you for your project. Great effort

I change some code to be able to logon with another credential (for client and server). 
I was planning to do a pull request. But saw you did an implementation yourself.

I want to adapt your implementation to able to use nuget and future releases, but these change are not in a nuget package yet. Also the TestClient (and TestServer) lacks an implementation.

Will you be able to do this in near future?

Regards!

**Comment by antiduh** [comment]
Yeah, I can publish an update tomorrow. What would you like to see in the TestClient and TestServer? Since those are only for demonstration, I didn't figure it'd be necessary to update them.

**Comment by IsaacBoy** [comment]
Hey thanks for this. Yea an example of using the un/password credentials you added would be really helpful

**Comment by antiduh** [comment]
Sorry this took a while to publish, work has been killing me. I've put out the new build on nuget, so go nuts. I didn't update the demo since I'm slim on time, but the usage is fairly straight-forward - check out the `PasswordCredential` class, which you would use in place of the previous credential classes.

I'll leave this open for a few days in case anybody has feedback on the new build

**Comment by oxygenius** [comment]
Hi Kevin.

Thank you very much. 

I think there is a bug in AuthData.cs

    internal enum NativeAuthDataFlag : int
    {
        Ansi = 1,

        Unicode = 1
    }

Unicode should be 2

**Comment by antiduh** [comment]
Finally fixed that enum. Closing this.

**Comment by Bosje** [comment]
Hi Kevin,

Can I get en ETA on when a new version will be released with this fix?
We are currently using a self maintained NuGet package.

Thank you for your work!

**Comment by antiduh** [comment]
@Bosje - All done. Sorry for the delay!
